apiVersion: v1
kind: Service
metadata:
  name: mongo
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: mongo-db
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017

  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - sh
            - -c
            - mongosh --eval "rs.initiate() && var cfg = rs.conf() && cfg.members[0].host='mongo-0.mongo:27017'&& rs.reconfig(cfg) && rs.add('mongo-1.mongo:27017') && rs.add('mongo-2.mongo:27017');"
            - mongod --bind_ip_all --replSet rs0

          
            
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: azure-vol
              mountPath: /mnt/azure
      volumes:
        - name: azure-vol
          persistentVolumeClaim:
            claimName: mongo-pvc
