apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  selector:
    matchLabels:
      app: reactapp
  replicas: 2
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: imageidentificationcon
          image: sumithpe/imageidentifront:latest
          ports:
            - containerPort: 80
