apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp1
spec:
  selector:
    matchLabels:
      app: reactapp1
  replicas: 2
  template:
    metadata:
      labels:
        app: reactapp1
    spec:
      containers:
        - name: imageidentificationcon
          image: sumithpe/imageidentifrontapp:31
          ports:
            - containerPort: 3000
