apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    matchLabels:
      app: reactapp
  replicas: 2
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: imageidentificationcon
          image: sumithpe/imagefrontidentification:32
          ports:
            - containerPort: 3000
      
      
