apiVersion: v1
kind: Service
metadata:
  name: reactservice
spec:
  type: LoadBalancer
  selector:
    app: reactapp
  clusterIP: 10.0.34.180
  ports:
    - targetPort: 3000
      protocol: TCP
      port: 3000
      nodePort: 32000
